# Generated by ivaldi

.PHONY: build run debug install test release lint

test:
	go test ./...

lint:
	golangci-lint run

build: lint test
run-ivaldi:
	go run cmd/ivaldi/main.go

run: run-ivaldi

debug:
	go run -race cmd/ivaldi/main.go &
	wait

install:
	go install ./cmd/ivaldi

release: build
	# TODO: Add your release steps or integration with goreleaser here
	echo "Release complete."
